#---
#- name: Prepare containers
#  hosts: all
#  gather_facts: false
#  tasks:
#
#    - name: Install python3 in Ubuntu
#      raw: |
#        apt-get update -y
#        apt-get install -y python3 python3-apt
#      when: "'ubuntu' in inventory_hostname"
#
#    - name: Install python3 in OracleLinux
#      raw: |
#        dnf install -y python3 python3-dnf
#      when: "'oracle' in inventory_hostname"


---
- hosts: all
  gather_facts: false
  tasks:
    - name: install python3
      raw: |
        (apt-get update -y && apt-get install -y python3 sudo) ||
        (dnf install -y python3 sudo)
